---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-scripts
  labels:
    app: {{ .Release.Name }}
data:
  create-keystore.sh: |-
{{ .Files.Get "kafka/scripts/create-keystore.sh" | indent 4 }}
  configure-topic.sh: |-
{{ .Files.Get "kafka/scripts/configure-topic.sh" | indent 4 }}
  permissions.txt: |-
{{ .Files.Get "kafka/scripts/permissions.txt" | indent 4 }}
  set-up-topic.sh: |-
{{ .Files.Get "kafka/scripts/set-up-topic.sh" | indent  4}}
  person-properties: |-
{{ .Files.Get "kafka/scripts/person-properties" | indent 4 }}