environment: dev
branch: main #overridden for branch deploys

service:
  port: 3000

replicaCount: 1

image:
  repo: quay.io/ukhomeofficedigital/
  tag: latest # this value will be overridden by drone.yml

env:
  kafka:
    - name: BOOTSTRAP_SERVER
      valueFrom:
        secretKeyRef:
          name: callisto-dev-bootstrap
          key: bootstrap_server1
    - name: AWS_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: callisto-dev-msk
          key: certificate_authority_access_keys
    - name: AWS_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: callisto-dev-msk
          key: certificate_authority_secret_keys
    - name: AWS_CERTIFICATE_AUTHORITY_ARN
      valueFrom:
        secretKeyRef:
          name: callisto-dev-msk
          key: certificate_authority_arn
    - name: TIMECARD_KEYSTORE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: callisto-dev-person-keystore
          key: password