mainContainerImage:
  repositoryName: callisto-person-restapi
  tag: latest # overwritten by deployments

service:
  containerPort: 9090

databaseMigrationImage:
  repositoryName: person-accruals-database
  tag: latest # overwritten by deployments

deploymentAnnotations:
  downscaler/uptime: Mon-Fri 08:00-20:00 Europe/London

db:
  secretKeyRefName: callistodev-rds
  schemaName: person

kafka:
  defaultTopic: callisto-person-people
  identity: person-restapi
  mskSecretKeyRefName: callisto-dev-msk
  bootstrapSecretKeyRefName: callisto-dev-bootstrap
  createTopics:
    topicNames: |-
      callisto-person-people
    permissions: |-
      --topic person --resource-pattern-type prefixed
      User:person-restapi-producer     Write       Allow
      User:person-restapi-producer     Describe    Allow

ingress:
  branch: main # overwritten by branch deploy
  host: person.dev.callisto-notprod.homeoffice.gov.uk
  tlsSecretName: callisto-person-tls
  corsOrigin: "https://*.dev.callisto-notprod.homeoffice.gov.uk"
