mainContainerImage:
  repositoryName: callisto-person-restapi
  tag: latest # overwritten by deployments

service:
  containerPort: 9090


databaseMigrationImage:
  repositoryName: person-accruals-database
  tag: latest # overwritten by deployments

deploymentAnnotations:
  downscaler/uptime: Mon-Fri 08:00-20:00 Europe/London

db:
  secretKeyRefName: callistodev-rds
  schemaName: person

kafka:
  defaultTopic: callisto-person-people
  identity: person-restapi
  mskSecretKeyRefName: callisto-dev-msk
  bootstrapSecretKeyRefName: callisto-dev-bootstrap

ingress:
  branch: main # overwritten by branch deploy
  host: person.dev.callisto-notprod.homeoffice.gov.uk
  tlsSecretName: callisto-person-tls
  corsOrigin: "https://*.dev.callisto-notprod.homeoffice.gov.uk"

env:
  database:
    - name: DATABASE_NAME
      valueFrom:
        secretKeyRef:
          name: callistodev-rds
          key: db_name
    - name: DATABASE_USERNAME
      valueFrom:
        secretKeyRef:
          name: callistodev-rds
          key: username
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: callistodev-rds
          key: password
    - name: DATABASE_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: callistodev-rds
          key: endpoint
    - name: DATABASE_PORT
      valueFrom:
        secretKeyRef:
          name: callistodev-rds
          key: port
  kafka:
    - name: BOOTSTRAP_SERVER
      valueFrom:
        secretKeyRef:
          name: callisto-dev-bootstrap
          key: bootstrap_server1
    - name: AWS_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: callisto-dev-msk
          key: certificate_authority_access_keys
    - name: AWS_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: callisto-dev-msk
          key: certificate_authority_secret_keys
    - name: AWS_CERTIFICATE_AUTHORITY_ARN
      valueFrom:
        secretKeyRef:
          name: callisto-dev-msk
          key: certificate_authority_arn
    - name: PERSON_KEYSTORE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: callisto-dev-person-keystore
          key: password
    - name: PERSON_TOPIC
      value: callisto-person-people