environment: dev
branch: main #overridden for branch deploys

service:
  port: 3000

replicaCount: 1

image:
  repo: quay.io/ukhomeofficedigital/
  tag: latest # this value will be overridden by drone.yml
  ecr_repo: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/callisto/
