mainContainerImage:
  repositoryName: callisto-person-restapi
  tag: latest # overwritten by deployments

service:
  containerPort: 9090

databaseMigrationImage:
  repositoryName: callisto-person-database
  tag: latest # overwritten by deployments

db:
  secretKeyRefName: callisto-prod-1
  schemaName: person

kafka:
  defaultTopic: callisto-person-people
  identity: person-restapi
  mskSecretKeyRefName: callisto-prod-msk
  bootstrapSecretKeyRefName: callisto-prod-bootstrap
  createTopics:
    topicNames: |-
      callisto-person-people
    permissions: |-
      --topic person --resource-pattern-type prefixed
      User:person-restapi-producer     Write       Allow
      User:person-restapi-producer     Describe    Allow
